### PR TITLE
Added EH,GG,YT,IM,JE countries dial code

### PR DESCRIPTION
**Pull request by fishman1986**
Hi there,

I fork this repository again, and create new pull request.

### CODE REVIEW

**Comment by jackocnr** [comment]
Can you tell me why you want to include these areas? Do we even have flags for them?

Apparently Western Sahara is a disputed territory, so I don't want to include that. Guernsey, Isle of Man and Jersey are all subsideries of England, and have the same intl dial code, so I don't see the point in adding them. Remember this is all extra weight in the plugin and it's really important to keep this as small as possible.

**Comment by fishman1986** [comment]
Can you tell me why you want to include these areas? Do we even have flags for them?
> Yes, we have.
According to the [ISO 3166-2|https://en.wikipedia.org/wiki/ISO_3166-2], they are officially assigned their own country codes.

**Comment by jackocnr** [comment]
Ok I have added a section to [data.js](https://github.com/Bluefieldscom/intl-tel-input/blob/master/src/js/data.js) detailing the list of regions that I have omitted and a reason why.

If you would like to challenge any of these reasons, please state clearly why you think it is worth adding to the plugin, and give links to examples of other country lists which also include that region.

**Comment by jackocnr** [comment]
You know what, I've changed my mind. If people from these regions identify that way, then we should support that.

**Comment by jackocnr** [comment]
Oh it seems that you have deleted your repository now, so I can't just re-open this pull request - I'm sorry about that. Is it easy to get it back?

**Comment by fishman1986** [comment]
New PR coming, https://github.com/Bluefieldscom/intl-tel-input/pull/295

**Pull request closed without merging**
