### PR TITLE
Added CommonJS support

### PR DESCRIPTION
**Pull request by callumacrae**
This is required to properly use this library with browserify without `window.$` being defined.

### CODE REVIEW

**Comment by jackocnr** [comment]
Could you please run `grunt js` to update the build files?

**Comment by callumacrae** [comment]
Done!

**Comment by callumacrae** [comment]
@jackocnr What do you want to happen with this PR?

**Comment by jackocnr** [comment]
Looks like there is a merge conflict - can you rebase? (if you have a conflict on a build file, just accept the upstream version then rebuild the project).

**Comment by callumacrae** [comment]
Done! I have absolutely no idea what happened to the build files when I rebased, but they should merge fine.

**Comment by jackocnr** [comment]
Thanks!

**Comment by callumacrae** [comment]
Thanks, when are you planning on a release?

**Comment by jackocnr** [comment]
Just did a v6.1.0 release.

**Comment by markus138** [comment]
how can I use it with browserify? I can require the lib normally, but 
> element.intlTelInput

is always undefined

**Pull request merged**
