### PR TITLE
Accessibility

### PR DESCRIPTION
**Pull request by brunops**
Make plugin accessible for tab navigation, using idea discussed in #195
Tried to follow all the code styles, added comments and tests.

The commit messages have detailed information of each change.
Let me know your thoughts.

### CODE REVIEW

**Comment by jackocnr** [comment]
Wow this is amazing thank you.

I just had a quick look and currently on Chrome, when you tab to the selected country, the blue border seems to go under the `input` on the right. There are 2 solutions to this (off the top of my head): either just add `z-index: 1;` to the `.flag-dropdown` (we need to consider this carefully as we've had z-index issues in the past with multiple instances overlapping each other), OR move the `tabindex` thing from the `.flag-dropdown` to the `.selected-flag`, which changes the blue outline thing when the dropdown is open: currently the whole dropdown has the blue outline, but if you move the tabindex, then it's only ever the selected-flag that has it. I'm not sure which makes more sense. Thoughts?

**Comment by brunops** [comment]
Cool! I'm glad you liked it.
Good catch, IMHO it makes more sense to keep the `tabindex` in `.flag-dropdown`, as you've mentioned it keep the blue outline over both the select and the list, which looks nice.
Adding the `z-index: 1;` to `.flag-dropdown` seems to have fixed it, but I'm not aware of the issue you've just mentioned, would you remember the steps to reproduce it?

**Comment by jackocnr** [comment]
Just have 2 inputs: one above the other, and instantiate the plugin on both, and check that opening the dropdown on the top goes over the bottom one properly. Does that make sense? The dropdown of the first input should go over the selected flag of the second input

**Comment by brunops** [comment]
Yes @jackocnr, I understand what you're saying now..
screen shot 2015-04-23 at 9 40 28 am

Not sure how to solve it.. only CSS fix I could think of was to have incremental `z-index` properties for each of the instances on the page (so first would be `1`, second `2` and so on..), but I don't like this solution, it'll probably introduce other issues.

Should we go with the `tabindex` on `.selected-flag` approach instead?

**Comment by jackocnr** [comment]
Yer I've looked into it and I don't think there's a solution to the z-index problem, so yer let's try moving the tabindex and I'll test that solution some more. Thanks man.

**Comment by brunops** [comment]
Just made the update, the outline is not as great as before, but the accessibility part is probably a bigger win.. let me know your thoughts.

**Comment by jackocnr** [comment]
Thank you so much!

**Pull request merged**
